Issue 4 delete an entry
bryanvaldovinos/code-journal pull request #9
Opened 2022-06-09 22:01 UTC by bryanvaldovinos

https://user-images.githubusercontent.com/103273265/172952528-919f48c7-9289-45a3-93fc-70dbd2c61848.mov

2022-06-09 22:04 UTC, codingcodymiller requested changes

2022-06-09 22:04 UTC, codingcodymiller commented on css/styles.css
> +  margin: 250px 525px;
Why this huge margin? There is likely a better way to do this.

2022-06-09 22:04 UTC, codingcodymiller commented on css/styles.css
> +.modal-button-2 {
Numbered class name? 😱

2022-06-09 22:04 UTC, codingcodymiller commented on css/styles.css
> +.space {
space what?

2022-06-09 22:04 UTC, codingcodymiller commented on js/main.js
> +        uList.getElementsByTagName('li')[i].replaceWith(entryTree(data.editing));
You should stick to `querySelector`

2022-06-09 22:04 UTC, codingcodymiller commented on js/main.js
> +      uList.getElementsByTagName('li')[i].remove();
You should stick to `querySelector`

2022-06-10 01:10 UTC, bryanvaldovinos commented
https://user-images.githubusercontent.com/103273265/172970308-c970926e-0655-4e0d-93ee-8cea73a70748.mov

2022-06-10 01:45 UTC, codingcodymiller approved these changes

2022-06-16 17:46 UTC, merged